version: 4
shared:
  environment:
    PACKAGE_DIR: src/github_security_alerts

jobs:
  validate_test:
    template: python/validate_unittest
    environment:
      TOX_ARGS: -p all --parallel-live
    requires: [~commit, ~pr]

  validate_lint:
    template: python/validate_lint
    requires: [~commit, ~pr]

  validate_codestyle:
    template: python/validate_codestyle
    requires: [~commit, ~pr]

  validate_safetydb:
    template: python/validate_safety
    requires: [~commit, ~pr]

  validate_security:
    template: python/validate_security
    requires: [~commit, ~pr]

  generate_version:
    template: python/generate_version
    requires: [~commit]

  publish_test_pypi:
    template: python/package_python
    environment:
      # Note, this step will not publish unless the TEST_PYPI_USER and TEST_PYPI_PASSWORD secrets are added to the screwdriver pipeline and
      # the Publish variable below is set to True
      PUBLISH: False
      TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    requires: [validate_test, validate_lint, validate_codestyle, validate_safetydb, validate_security, generate_version]

